//
// This file was generated by the JavaTM Architecture for XML 
// Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon 
// recompilation of the source schema. 
// Generated on: 2009.09.15 at 05:03:16 PM CDT 
//


package mx.com.att.vo.orange;

import java.io.Serializable;



public class FleetVO
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected Integer fleetIdNew;
    protected Integer fleet;
    protected Integer tamanoFlota;
    protected String custCode;
    protected Integer urbanId;
    protected Integer fleetId;
    protected Long fleetRef;
    protected Integer id;
    protected String subMarketRef;
    protected Integer marketRef;
    protected Long idTransaccion;

    /**
     * Gets the value of the fleetIdNew property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFleetIdNew() {
        return fleetIdNew;
    }

    /**
     * Sets the value of the fleetIdNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFleetIdNew(final Integer value) {
        this.fleetIdNew = value;
    }

    /**
     * Gets the value of the fleet property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFleet() {
        return fleet;
    }

    /**
     * Sets the value of the fleet property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFleet(final Integer value) {
        this.fleet = value;
    }

    /**
     * Gets the value of the tamanoFlota property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTamanoFlota() {
        return tamanoFlota;
    }

    /**
     * Sets the value of the tamanoFlota property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTamanoFlota(final Integer value) {
        this.tamanoFlota = value;
    }

    /**
     * Gets the value of the custCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustCode() {
        return custCode;
    }

    /**
     * Sets the value of the custCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustCode(final String value) {
        this.custCode = value;
    }

    /**
     * Gets the value of the urbanId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUrbanId() {
        return urbanId;
    }

    /**
     * Sets the value of the urbanId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUrbanId(final Integer value) {
        this.urbanId = value;
    }

    /**
     * Gets the value of the fleetId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFleetId() {
        return fleetId;
    }

    /**
     * Sets the value of the fleetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFleetId(final Integer value) {
        this.fleetId = value;
    }

    /**
     * Gets the value of the fleetRef property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFleetRef() {
        return fleetRef;
    }

    /**
     * Sets the value of the fleetRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFleetRef(final Long value) {
        this.fleetRef = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(final Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the subMarketRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubMarketRef() {
        return subMarketRef;
    }

    /**
     * Sets the value of the subMarketRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubMarketRef(final String value) {
        this.subMarketRef = value;
    }

    /**
     * Gets the value of the marketRef property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMarketRef() {
        return marketRef;
    }

    /**
     * Sets the value of the marketRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMarketRef(final Integer value) {
        this.marketRef = value;
    }

    /**
     * Gets the value of the idTransaccion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdTransaccion() {
        return idTransaccion;
    }

    /**
     * Sets the value of the idTransaccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdTransaccion(final Long value) {
        this.idTransaccion = value;
    }

}
